#!/bin/bash

#PS4='Line ${LINENO}: '
#set -x

FREQ="${1:-500}"
SPAN="${2:-20}"
POWERLEVEL="${3:-4}"
echo $FREQ $SPAN $POWERLEVEL

while [ $FREQ -lt 6000000000 ] 
do
    echo $FREQ $SPAN $POWERLEVEL

    python3  ../python_client/testapp.py --cmd "StartCW" --freq $FREQ --span $SPAN --power-level $POWERLEVEL
    if [[ $? -ne 0 ]]; then exit; fi

    sleep 5

    python3  ../python_client/testapp.py --cmd "StopGen" 
    if [[ $? -ne 0 ]]; then exit; fi

    sleep 1
    ((FREQ=FREQ + 500))



done
