#!/bin/bash

PS4='Line ${LINENO}: '
#set -x

check_result()
{
    if [[ $? -ne 0 ]]
    then 
        exit 
    fi
}

echo "address is " ${ADDR='127.0.0.1'} ${PORT=10000}


echo  debug level - $1
python3  ../util/testapp.py --cmd "setServerDebug" --server-addr $ADDR --tcp-port $PORT --debug-level $1 
check_result 






