#!/bin/python3


import socket
import sys

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
server_address = ('localhost', 10000)
print('connecting to ' + server_address[0] + ' port ' + str(server_address[1]))
sock.connect(server_address)

try:
    pktnum = 0
    while pktnum < 10:
        # Send data
        message = 'This is the message ' + str(pktnum) +  ' It will be repeated.'
        print('sending: ', message)
        sock.sendall(message.encode())

        # Look for the response
        amount_received = 0
        amount_expected = len(message)

        while amount_received < amount_expected:
            data = sock.recv(1024)
            amount_received += len(data)
            print( 'received: ', data.decode())
        pktnum += 1

finally:
    print('closing socket')
    sock.close()
