#!/bin/bash

PS4='Line ${LINENO}: '
#set -x

check_result()
{
    if [[ $? -ne 0 ]]
    then 
        exit 
    fi
}

client_debug_level=3

DEBUG="--debug-level $client_debug_level"

#../testapp_server &

#PID=$!
#echo $PID

#sleep 2


python3  ../testapp.py --cmd "setServerDebug"  --debug-level 0
check_result

echo "connecting to RFE of type BOTH"
python3  ../testapp.py --cmd "connectRFE" --rfetype "BOTH" $DEBUG 
check_result

sleep 1
while :
do
    for i in {0..7}
    do
        echo " "
        echo "starting test with power level at $i"
        python3  ../testapp.py --cmd "StartCW" --freq 1000 --power-level $i $DEBUG 
        check_result 
        sleep 3

        python3  ../testapp.py --cmd "PeakSearch" --span 40 --start-freq 980 --stop-freq 1020 --verbose-level 4 $DEBUG 
        check_result 

        sleep 1

        python3  ../testapp.py --cmd "StopCW" $DEBUG 
        check_result 
    done
done

python3  ../testapp.py --cmd "disconnectRFE"  $DEBUG 
check_result 




