#!/bin/python3

def debug_print(val1, val2 = None, val3 = None, val4 = None):


    out = str(val1)

    if val2 != None:
        out = out + " " + str(val2)


    if val3 != None:
        out = out + " " + str(val3)

    print(out)



print(str("starting"))

debug_print("starting")
debug_print(-199.99)
debug_print(-199.99, "hello")
debug_print(-199.99, "hello", -85)
    
