#!/bin/python3
from usbconnect import *

SERIALPORT = "/dev/ttyUSB1"
#SERIALPORT = '/dev/ttyUSB0'    #serial port identifier, use None to autodetect
#SERIALPORT = '/dev/ttyUSB1'    #serial port identifier, use None to autodetect
BAUDRATE = 500000


objcon = USBConnect() 
objcon.VerboseLevel = 10
objcon.GetConnectedPorts()
objcon.ConnectPort(SERIALPORT, BAUDRATE)
objcon.SendCommand_GeneratorRFPowerOFF()
