#!/bin/python3

#---------Imports

import time
import math
import array as arr

import RFExplorer
#print(RFExplorer.__file__)
from RFExplorer import RFE_Common


import tkinter as tk
from tkinter import ttk
from tkinter import *
from tkinter.messagebox import Message

import numpy as np

import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

#---------End of imports



from tkinter import Frame,Label,Entry,Button

DEBUG = False

BAUDRATE = 500000

SPAN_SIZE_MHZ = 50           #Initialize settings
START_SCAN_MHZ = 975
STOP_SCAN_MHZ = START_SCAN_MHZ + SPAN_SIZE_MHZ
SWEEPPOINTS = 112
SWEEPDATA = (SWEEPPOINTS + 1) * 16
RESET = True

# test settings to make sure they are valid
def ControlSettings(objAnalazyer):
    global SPAN_SIZE_MHZ
    """This functions check user settings
    """
    SpanSizeTemp = None
    StartFreqTemp = None
    StopFreqTemp =  None

    #print user settings
    if DEBUG:
        print("User settings:" + "Span: " + str(SPAN_SIZE_MHZ) +"MHz"+  " - " + "Start freq: " + str(START_SCAN_MHZ) +"MHz"+" - " + "Stop freq: " + str(STOP_SCAN_MHZ) + "MHz")

    #Control maximum Span size
    if(objAnalazyer.MaxSpanMHZ <= SPAN_SIZE_MHZ):
        showinfo("Error", "Invalid span size, Max is " + str(objAnalazyer.MaxSpanMHZ)+"MHz", 4)
    else:
        objAnalazyer.SpanMHZ = SPAN_SIZE_MHZ
        SpanSizeTemp = objAnalazyer.SpanMHZ
    if(SpanSizeTemp):
        #Control minimum start frequency
        if(objAnalazyer.MinFreqMHZ > START_SCAN_MHZ):
            if DEBUG:
                print("Min Start freq: " + str(objAnalazyer.MinFreqMHZ)+"MHz")
        else:
            objAnalazyer.StartFrequencyMHZ = START_SCAN_MHZ
            StartFreqTemp = objAnalazyer.StartFrequencyMHZ
        if(StartFreqTemp):
            #Control maximum stop frequency
            if(objAnalazyer.MaxFreqMHZ < STOP_SCAN_MHZ):
                if DEBUG:
                    print("Max Start freq: " + str(objAnalazyer.MaxFreqMHZ)+"MHz")
            else:
                if((StartFreqTemp + SpanSizeTemp) > STOP_SCAN_MHZ):
                    if DEBUG:
                        print("Max Stop freq (START_SCAN_MHZ + SPAN_SIZE_MHZ): " + str(STOP_SCAN_MHZ) +"MHz")
                else:
                    StopFreqTemp = (StartFreqTemp + SpanSizeTemp)

    return SpanSizeTemp, StartFreqTemp, StopFreqTemp

#This class creates the window to modify the frequency
class FreqWindow(Toplevel):

    def __init__(self, master = None):
        self.win = Toplevel

    #if the user hits enter while inside this window
    def enterhandler(self, e):
        if DEBUG:
            print("FreqWindow enterhandler")

        app.freqwindow.get_entry()


    # draw the new window
    def draw_window(self):
        super().__init__(master = None)
        self.title("Frequency")
        self.geometry("600x200")
        self.columnconfigure(3, weight=2)
        freqlabel = Label(self, text ="Frequency (MHz): ", font=("Arial", 16));
        freqlabel.grid(row=0, column=0)
        
        self.freqentry = Entry(self, width = 15, font=("Arial", 16))
        self.freqentry.bind('<Return>', self.enterhandler)

        # put the cursor inside the entry
        self.freqentry.focus_set()
        center_freq = int(((START_SCAN_MHZ) + (SPAN_SIZE_MHZ / 2)) ) 
        self.freqentry.insert(1, str(center_freq))
        self.freqentry.grid(row=0, column=1)


    #The user hit enter
    def get_entry(self):
        global START_SCAN_MHZ, STOP_SCAN_MHZ, SPAN_SIZE_MHZ
       
        new_center = int(self.freqentry.get())

        new_start = new_center - (SPAN_SIZE_MHZ / 2)
        new_stop = new_center + (SPAN_SIZE_MHZ / 2)

        # validate that the new value is good
        if(objRFE.MinFreqMHZ > new_start):
            msg = "Incorrect Start Frequency " + str(new_start) + " Min Start freq: " + str(objRFE.MinFreqMHZ)+"MHz"
            showinfo("Error", msg, 4) 
            self.destroy()
            return 

        if(objRFE.MaxFreqMHZ < new_stop):
            msg = "Incorrect Stop Frequency " + str(new_stop) + " Max Stop freq: " + str(objRFE.MaxFreqMHZ)+"MHz"
            showinfo("Error", msg, 4) 
            self.destroy()
            return 
        
        START_SCAN_MHZ = new_start
        STOP_SCAN_MHZ = new_stop

        #start all over with a new window
        app.init_window(content)

        # delete the freq window
        self.destroy()

# This class creates the window to modify the span
class SpanWindow(Toplevel):

    def __init__(self, master = None):
        self.win = Toplevel

    # called when a user hits enter
    def enterhandler(self, e):
        if DEBUG:
            print("SpanWindow enterhandler")

        app.spanwindow.get_entry()

   
    # draw the window
    def draw_window(self):
        super().__init__(master = None)
        self.title("Span")
        self.geometry("400x400")
        self.columnconfigure(3, weight=2)
        spanlabel = Label(self, text ="Span (Mhz): ", font=("Arial", 16));
        spanlabel.grid(row=0, column=0)
        
        self.spanentry = Entry(self, width = 15, font=("Arial", 16))
        self.spanentry.bind('<Return>', self.enterhandler)
        self.spanentry.focus_set()
        span = SPAN_SIZE_MHZ 
        self.spanentry.insert(1, str(span))
        self.spanentry.grid(row=0, column=1)

    # the user hit enter in this window
    def get_entry(self):
        global START_SCAN_MHZ, STOP_SCAN_MHZ, SPAN_SIZE_MHZ
       
        new_span = int(self.spanentry.get())

        # Validate the span
        if(objRFE.MaxSpanMHZ <= new_span):
            showinfo("Error", "Invalid span size, Max is " + str(objRFE.MaxSpanMHZ)+"MHz", 4)
            self.destroy()
            return 

        # calculate the new start and stop freq from the span
        new_center = int(self.freqentry.get())

        new_start = new_center - (new_span / 2)
        new_stop = new_center + (new_span / 2)

        # validate that the new value is good
        if(objRFE.MinFreqMHZ > new_start):
            msg = "Incorrect Start Frequency " + str(new_start) + " Min Start freq: " + str(objRFE.MinFreqMHZ)+"MHz"
            showinfo("Error", msg, 4) 
            self.destroy()
            return 

        if(objRFE.MaxFreqMHZ < new_stop):
            msg = "Incorrect Stop Frequency " + str(new_stop) + " Max Stop freq: " + str(objRFE.MaxFreqMHZ)+"MHz"
            showinfo("Error", msg, 4) 
            self.destroy()
            return 
        
        START_SCAN_MHZ = new_start
        STOP_SCAN_MHZ = new_stop
        SPAN_SIZE_MHZ = new_span

        # delete this window
        self.destroy()

        # start all over with a new window with these parameters
        app.init_window(content)


# this is the main window
class Window(Frame):
    def __init__(self, master = None):
        Frame.__init__(self, master)
        self.master = master

        #get and store the two windows that update things
        self.freqwindow = FreqWindow(self.master)
        self.spanwindow = SpanWindow(self.master)

    # RFExplorer contains the received sweep data and that object knows 
    # the amplitude and frequency for each data point
    def GetData(self, sweepdata, tot):
        amp = arr.array('f',[])
        freq = arr.array('f',[])
        for nDataPoint in range(tot):
            val = sweepdata.GetAmplitudeDBM(nDataPoint, None, False)
            amp.append(val)
            freq.append(sweepdata.GetFrequencyMHZ(nDataPoint))

        return freq, amp


    # this is called by matplotlib's animate loop animate.FuncAnimation()
    # it is called every 40ms
    def animate(self,i):
        self.objSweep=None

        # wait till we get a new sweepdata msg
        objRFE.ProcessReceivedString(True);

        # see if we actually got a new one
        num = objRFE.SweepData.Count 
        if self.numitems != num:
            self.numitems = num
            if (self.numitems > 0):
                # get the object with the latest msg
                objSweep=objRFE.SweepData.GetData(self.numitems-1)
                tot=objSweep.TotalDataPoints

                # extract the freq and amp arrays from the data
                self.freq, self.amp = self.GetData(objSweep, tot)
                if DEBUG:
                    if i % 10 == 0:
                        print("in animate")
                        print("config start", objRFE.StartFrequencyMHZ, "config stop ", objRFE.StopFrequencyMHZ )
                        print("Freq min ", min(self.freq), " max ", max(self.freq))
                        print("Amp min ", min(self.amp), " max ", max(self.amp))

                 
                self.line.set_ydata(self.amp)  # update the data
                self.line.set_xdata(self.freq)  # update the data

                # display the peak value arrow
                self.ann.remove()
                ymax = max(self.amp)

                # get the position in the array of the ymax value
                xpos = np.argmax(self.amp)
                xmax = self.freq[xpos]

                xtextpos = 20
                ytextpos = 20
                
                # make sure the text goes on the left side when it is pointing 
                # near the right side of the plot
                greater_textsize = 200
                if xpos > SWEEPPOINTS - 10:
                    xtextpos = - greater_textsize
                
               
                # get the frequency with 3 decimal places
                xmax_int = int(xmax * 1000)
                xmax = xmax_int / 1000 
               
                # display the peak text and arrow
                display_text = "x = " + str((xmax)) + " y = " + str(ymax)
                self.ann = self.ax.annotate(display_text, xy=(xmax, ymax), 
                        textcoords='offset pixels', xytext=(xtextpos, ytextpos), 
                        arrowprops=dict(arrowstyle="->", facecolor='black'),)
                objRFE.CleanSweepData()

        return self.line,


    # initialize the main window
    def init_window(self, content):
        self.objSweep=None
        # store the freq and span window
        self.freqwindow = FreqWindow(self.master)
        self.spanwindow = SpanWindow(self.master)
        
        self.buttonFreq = Button(content,text="Frequency")
        # Following line will bind click event
        # On any click left / right button
        # of mouse a new window will be opened
        self.buttonFreq.bind("<Button>",
                 lambda e: self.freqwindow.draw_window())
        self.buttonFreq.grid(row=0,column=3, sticky= 'nsew')

        self.buttonSpan = Button(content,text="Span")
        self.buttonSpan.bind("<Button>",
                 lambda e: self.spanwindow.draw_window())
        self.buttonSpan.grid(row=1,column=3, sticky='nsew')

        # create the inner canvas to display plot to
        self.fig = plt.Figure()
        self.ax = self.fig.add_subplot(111)
        self.canvas = FigureCanvasTkAgg(self.fig, master=frame)
        self.canvas.get_tk_widget().grid(column=0,row=0, sticky = 'nsew')

        # build the plot
        self.build_plot(frame)


    def build_plot(self, frame):
        # these things must be done before you can start processing the sweeppoints
        
        #Request RF Explorer configuration
        objRFE.SendCommand_RequestConfigData()

        #Wait to receive COFF:02
        while(objRFE.ActiveModel == RFExplorer.RFE_Common.eModel.MODEL_NONE):
            objRFE.ProcessReceivedString(True)    #Process the received configuration

        #If object is an analyzer, we can scan for received sweeps
        if(not objRFE.IsAnalyzer()):
            showinfo("Error", "Not an analyzer, exiting...", 2)
            cleanup()

        #Verify the Control settings
        SpanSize, StartFreq, StopFreq = ControlSettings(objRFE)

        if(SpanSize and StartFreq and StopFreq):
            nInd = 0

            # Program the configuration into device
            objRFE.UpdateDeviceConfig(StartFreq, StopFreq)
            objRFE.ProcessReceivedString(True)

            # wait until we have indication that the new configuration is in device
            while (StartFreq != objRFE.StartFrequencyMHZ):
                objRFE.ProcessReceivedString(True)

            # wait until we have received data
            self.numitems = objRFE.SweepData.Count - 1
            while (self.numitems <= 0):
                objRFE.ProcessReceivedString(True);
                self.numitems = objRFE.SweepData.Count - 1
           
            # display the new config info
            if DEBUG:
                print("config min", objRFE.StartFrequencyMHZ, "config max ", objRFE.StopFrequencyMHZ )

            # process the new data
            if (self.numitems > 0):
                # get the singular message from the object
                self.objSweep=objRFE.SweepData.GetData(self.numitems)
                tot=self.objSweep.TotalDataPoints

                # put the data into the freq and amp arrays
                self.freq, self.amp = self.GetData(self.objSweep, tot)

                if DEBUG:
                    print("Freq min ", min(self.freq), " max ", max(self.freq))
                    print("Amp min ", min(self.amp), " max ", max(self.amp))

                # build the plot
                self.line, = self.ax.plot(self.freq, self.amp)        
                self.ax.axis([StartFreq, StopFreq, min(self.amp) - 10, 0 ])

                # create the annotation
                ymax = max(self.amp)
                xpos = np.argmax(self.amp)
                xmax = self.freq[xpos]
                display_text = "x = " + str(int(xmax)) + " y = " + str(ymax)
                self.ann = self.ax.annotate(display_text, xy=(xmax, ymax), 
                        xytext=(xmax+5, ymax + 5), arrowprops=dict(arrowstyle="->", 
                        facecolor='black'),)
            else: 
                if DEBUG:
                    print("somethings wrong")
        else:
            if DEBUG:
                print("Error: settings are wrong.\nPlease, change and try again")
        

        self.ani = animation.FuncAnimation(self.fig, self.animate, None, interval=25, blit=False)


# if the enter is hit in the main window this gets called
def enterhandler(e):
    if DEBUG:
        print("enterhandler")

    go()


# The user hit enter after picking a port
def go():
    global app, user_entry
    portno = int(user_entry.get())

    # verify the entered number
    if portno >= len(objRFE.m_arrValidCP2102Ports) or portno < 0:
        showinfo("Error", "Error: Invalid Port Number " + str(portno) , 2)
        return

    else:
        PortName = objRFE.m_arrValidCP2102Ports[portno].device
        if DEBUG:
            print("Selected name", PortName)

    #Connect to available port
    objRFE.ConnectPort(PortName, BAUDRATE)
    if DEBUG:
        print("Connected...")

    # remove the labels for the various ports so we can display that we are resetting 
    # the device
    for obj in label:
        obj.after(10, obj.destroy())
    
    user_label2 = Label(current_frame, text= "Resetting device ...", font=("Arial", 16))
    user_label2.grid(row=1, column=0, padx=10, pady=10, sticky="w")
    current_frame.pack(fill="both", expand=True)

    # if configured reset the device 
    if RESET:
        if DEBUG:
            print("Resetting device...")

        #Reset the unit to start fresh
        objRFE.SendCommand("r")

        #Wait for unit to notify reset completed
        while(objRFE.IsResetEvent):
            pass

        #Wait for unit to stabilize
        # for some reason we need to do a messagebox to get this to work.
        showinfo("Info", "Resetting Device", None)
        time.sleep(4)

    # build the main window
    content, frame = build_window()

    # initialize the main window
    app.init_window(content)  


# Display the window to let the user select the port desired and pick one
def GetPort():
    global app, current_frame, user_entry

    # delete one if it exists
    current_frame.destroy()
    frame = Frame(root)
    current_frame = frame

    # for some reason when it only goes through the for loop once if it 
    # deletes something.  So this while loop fixes that.
    done = False
    while (not done):
        deleted = False

        for objPort in objRFE.m_arrValidCP2102Ports:
            if (objPort.device == "/dev/ttyAMA0"):
                deleted = True
                objRFE.m_arrValidCP2102Ports.remove(objPort)

            if (objPort.device == "/dev/ttySKIQ_UART0"):
                deleted = True
                objRFE.m_arrValidCP2102Ports.remove(objPort)

            if (objPort.device == "/dev/ttySKIQ_UART1"):
                deleted = True
                objRFE.m_arrValidCP2102Ports.remove(objPort)

            if (objPort.device == "/dev/ttyS4") :
                deleted = True
                objRFE.m_arrValidCP2102Ports.remove(objPort)

        if deleted == False:
            done = True

    # see if we have more than one valid port, if so we need to display a window with the
    # choices
    if len(objRFE.m_arrValidCP2102Ports) > 1:

        # print the title of the window
        title = Label(current_frame, text= "Available Ports:", font=("Arial", 16))
        title.grid(row=0, column=1, padx=10, pady=10, sticky="ew")

        # build labels that contain each available port
        ctr = 0
        for objPort in objRFE.m_arrValidCP2102Ports:
            tmp_txt = str(ctr) + "     " +  objPort.device
            label.append(Label(current_frame, text=tmp_txt, font=("Arial", 16)))
            # Entry widgets in the row whose index is idx
            label[ctr].grid(row=ctr+1, column=0, padx=10, pady=10, sticky="w")
            ctr += 1
        

        # Display the label that tells the user what to do
        user_label = Label(current_frame, text= "Enter Port Number:", font=("Arial", 16))
        user_label.grid(row=ctr+2, column=0, padx=10, pady=10, sticky="w")

        # build the Entry box for them to enter it.
        user_entry = Entry(current_frame, width=5, font=("Ariel", 16))
        user_entry.grid(row=ctr+2, column=1, padx=10, pady=10)

        # put the cursor inside the entry box
        user_entry.focus_set()

        # display it
        current_frame.pack(fill="both", expand=True)

    # if there is exactly one port no need to select it, connect to it
    elif len(objRFE.m_arrValidCP2102Ports) == 1:
        PortName = objRFE.m_arrValidCP2102Ports[0].device
        if DEBUG:
            print("Selected name", PortName)

        #Connect to available port
        objRFE.ConnectPort(PortName, BAUDRATE)
        if DEBUG:
            print("Connected...")

        # if configured to reset, reset it and display that on the window.
        if RESET:
            user_label = Label(current_frame, text= "Resetting device ...", 
                    font=("Arial", 16))
            user_label.grid(row=2, column=0, padx=10, pady=10, sticky="w")
            
            # display it
            current_frame.pack(fill="both", expand=True)

            #Reset the unit to start fresh
            objRFE.SendCommand("r")

            #Wait for unit to notify reset completed
            while(objRFE.IsResetEvent):
                pass

            #Wait for unit to stabilize
            showinfo("Info", "Resetting Device", None)
            time.sleep(4)

        # build the main window
        content, frame = build_window()

        # initialize the main window
        app.init_window(content) 

    else: #no valid ports
        showinfo("Error", "No Valid Ports Found", 5)
        
        #remove this window
        root.destroy()

        # leave
        cleanup()
    
    return True

# used to display a message box describing the info
def showinfo(msgtitle, text, waittime):
    newroot = Tk()

    
    if waittime != None:
        newroot.after(waittime * 1000, newroot.destroy)
    else:
        # if waittime is None then we just quickly display the box and move on
        newroot.after(10, newroot.destroy)

    # make this window small so it can't be seen under the message box
    # there is no way to place the message box itself so we place the window
    newroot.geometry('10x10+200+200')

    # create and show the message box
    try:
        Message(title=msgtitle, message=text, master=newroot).show()
    except TclError:
        pass

# build the bottom layer window
def build_window():
    global content, frame

    # destroy it if it already exists
    current_frame.destroy()

    root.geometry("800x500")

    # make the inner frame that holds the plot
    content = ttk.Frame(root, padding=(3,3,12,12))

    # make the outer frame with a ridge
    frame = ttk.Frame(content, borderwidth=5, relief="ridge", width=200, height=100)

    content.grid(column=0, row=0, sticky='nsew')
    frame.grid(column=0, row=0, columnspan=3, rowspan=2, sticky='nsew')

    # setup all the configuration of the rows and columns
    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)
    frame.columnconfigure(0, weight=1)
    frame.rowconfigure(0, weight=1)
    content.columnconfigure(0, weight=3)
    content.columnconfigure(1, weight=3)
    content.columnconfigure(2, weight=3)
    content.columnconfigure(3, weight=1)
    content.rowconfigure(0, weight=1)
    content.rowconfigure(1, weight=1)

   
    return content, frame

# if something goes wrong go here
def cleanup():
    # kill the main window
    root.destroy

    # close RFE
    objRFE.Close()

    # leave
    exit()

# list of port labels
label = []

# create the RFE object
objRFE = RFExplorer.RFECommunicator()

# Get the connected ports tat RFE can see
objRFE.GetConnectedPorts()

# determine RFE verbose level
objRFE.VerboseLevel = 0

# this has to be the same as in the sigann.desktop file inside /usr/share/applications/
# so it can be selected by the Ubuntu chooser
root = Tk(className='annName')

# main window title and location
root.wm_title('RFE Signal Analyzer')
root.geometry('550x350+100+200')

# bind the enterhandler to the Return key in the main window.
root.bind('<Return>', enterhandler)

# unsure here
current_frame = Frame(root)
app = Window(root)

# go get the USB port the user wants
GetPort()

# spin on the tkinter mainloop
tk.mainloop()

# if this ends for any reason close up RFE 
objRFE.Close()
