#!/bin/python3

import tkinter as tk


"""
label  = tk.Label(
    text="Hello, Tkinter",
    foreground="white",
    background="black",
    width=50,
    height=10)


button  = tk.Button(
    text="click me",
    foreground="yellow",
    background="blue",
    width=25,
    height=5)


entry = tk.Entry(fg="yellow", bg="blue", width=40) 

#button.pack()
label.pack()
entry.pack()
entry.insert(0, "name?")
txt = entry.get()
print(txt)
"""
"""
border_effects = {
    "flat": tk.FLAT,
    "sunken": tk.SUNKEN,
    "raised": tk.RAISED,
    "groove": tk.GROOVE,
    "ridge": tk.RIDGE,
}

window = tk.Tk()

for relief_name, relief in border_effects.items():
    frame = tk.Frame(master=window, relief=relief, borderwidth=5)
    frame.pack(side=tk.LEFT)
    label = tk.Label(master=frame, text=relief_name)
    label.pack()
"""
"""
window = tk.Tk()

for i in range(3):
    for j in range(3):
        window.columnconfigure(i, weight=3, minsize=75)
        window.rowconfigure(i, weight=2, minsize=50)
        frame = tk.Frame(
            master=window,
            relief=tk.RIDGE,
            borderwidth=1
        )
        frame.grid(row=i, column=j, padx=5, pady=5)
        label = tk.Label(master=frame, text=f"Row {i}\nColumn {j}")
        label.pack( padx=5, pady=5)
"""

def increase():
    value = int(lbl_value["text"])
    lbl_value["text"] = f"{value + 1}"

def decrease():
    value = int(lbl_value["text"])
    lbl_value["text"] = f"{value - 1}"
    
window = tk.Tk()


window.rowconfigure(0, minsize=50, weight=1)
window.columnconfigure([0, 1, 2], minsize=50, weight=1)

btn_decrease = tk.Button(master=window, text="-", command=decrease)
btn_decrease.grid(row=0, column=0, sticky="nsew")

lbl_value = tk.Label(master=window, text="0")
lbl_value.grid(row=0, column=1)

btn_increase = tk.Button(master=window, text="+", command=increase)
btn_increase.grid(row=0, column=2, sticky="nsew")

window.mainloop()
