#!/bin/python3

import signal

from tkinter import * 
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, 
NavigationToolbar2Tk)
import matplotlib.pyplot as plt

def handler(signum, frame):
    global running

    print("ending...")
    running = False


# plot function is created for 
# plotting the graph in 
# tkinter window
def plot():
    global running
    varrange = 101
    # the figure that will contain the plot
    fig = Figure(figsize = (5, 5),
                 dpi = 100)
  
    # list of squares
    y = [i**2 for i in range(varrange)]
  
    # adding the subplot
    plot1 = fig.add_subplot(111)
    # creating the Tkinter canvas
    # containing the Matplotlib figure
    canvas = FigureCanvasTkAgg(fig,
                               master = window)  
    canvas.draw()
  
    # placing the canvas on the Tkinter window
    canvas.get_tk_widget().pack()
  
    # creating the Matplotlib toolbar
    toolbar = NavigationToolbar2Tk(canvas,
                                       window)
    while running == True:
        fig.clf()

        # list of squares
        y = [i**2 for i in range(varrange)]
      
        # plotting the graph
        plot1.plot(y)
      
        toolbar.update()
      
        # placing the toolbar on the Tkinter window
        canvas.get_tk_widget().pack()

        varrange += 10
        
        plt.pause(0.01)


running = True
signal.signal(signal.SIGINT, handler)

# the main Tkinter window
window = Tk()
  
# setting the title 
window.title('Plotting in Tkinter')
  
# dimensions of the main window
window.geometry("500x500")
  
# button that displays the plot
plot_button = Button(master = window, 
                     command = plot,
                     height = 2, 
                     width = 10,
                     text = "Plot")
  
# place the button 
# in main window
plot_button.pack()
  
# run the gui
window.mainloop()
