#!/bin/python3

# Import module
from tkinter import *
 
# Create object
root = Tk()
 
# Adjust size
root.geometry("500x500")
 

current_frame = Frame(root)

text=Text(root)
text.place(relx = 0.5, rely = 0.5, anchor = 'center')
#text.grid(column = 0, row = 5, sticky = 'nwes')

# Configure the alignment of the text
text.tag_configure("tag_name", justify='center', font=("Ariel",15))

# Insert a Demo Text
text.insert("1.0", "Connecting...")

# Add the tag in the given text
text.tag_add("tag_name", "1.0", "end")
text.place(relx = 0.5, rely = 0.5, anchor = 'center')
text.pack()


 
# Execute tkinter
root.mainloop()
