#!/bin/python3


import tkinter as tk

def start():
    print("submit")
    for idx, text in enumerate(labels):
        value = entry[idx].get()
        print(labels[idx], "\t", value)

def clear():
    print("clear")
    for idx, text in enumerate(labels):
        entry[idx].delete(0, tk.END)

def stop():
    print("stop")

# Create a new window with the title "Address Entry Form"
window = tk.Tk()
window.title("Frequency Sweep")


# Create a new frame `frm_gen` to contain the Label
# and Entry widgets for entering address information
#frm_gen = tk.Frame(relief=tk.RAISED, borderwidth=10)
frm_gen = tk.Frame(borderwidth=10)
# Pack the frame into the window
frm_gen.pack()

# List of field labels
labels = [
    "Start Freq MHz:", 
    "Power Level (0 - 3):",
    "Number of Steps:",
    "Step Time in ms:",
]

entry = []

# Loop over the list of field labels
for idx, text in enumerate(labels):
#    window.columnconfigure(0, weight=1, minsize=250)
#    window.columnconfigure(1, weight=1, minsize=250)
#    window.rowconfigure(idx, weight=1, minsize=100)

    # Create a Label widget with the text from the labels list
    label = tk.Label(master=frm_gen, text=text)
    # Create an Entry widget
    entry.append(tk.Entry(master=frm_gen, width=20))
    # Use the grid geometry manager to place the Label and
    # Entry widgets in the row whose index is idx
    label.grid(row=idx, column=0, padx=10, pady=10, sticky="e")
#    entry.grid(row=idx, column=1)
    entry[idx].grid(row=idx, column=1, padx=10, pady=10)

# Create a new frame `frm_buttons` to contain the
# Submit and Clear buttons. This frame fills the
# whole window in the horizontal direction and has
# 5 pixels of horizontal and vertical padding.
frm_buttons = tk.Frame()
frm_buttons.pack(fill=tk.X, ipadx=5, ipady=5)

# Create the "Submit" button and pack it to the
# right side of `frm_buttons`
btn_submit = tk.Button(master=frm_buttons, text="Start Sweep", command=start)
btn_submit.pack(side=tk.RIGHT, padx=10, ipadx=10)

# Create the "Stop" button and pack it to the
# right side of `frm_buttons`
btn_clear = tk.Button(master=frm_buttons, text="Stop Sweep", command=stop)
btn_clear.pack(side=tk.RIGHT, padx=10, ipadx=10)

# Create the "Clear" button and pack it to the
# right side of `frm_buttons`
btn_clear = tk.Button(master=frm_buttons, text="Clear", command=clear)
btn_clear.pack(side=tk.RIGHT, padx=10, ipadx=10)

# Start the application
window.mainloop()
