#!/bin/python3

import time
import tkinter as tk
from tkinter import ttk
from tkinter import *
from tkinter.messagebox import Message



window = tk.Tk()

window.columnconfigure(0, weight=2, minsize=250)
window.rowconfigure([0,1], weight=2, minsize=100)
frame = tk.Frame(
    master=window,
    relief=tk.RIDGE,
    borderwidth=1
)
#defines space between row and edge
frame.grid(row=0, padx=50, pady=5)

#puts text inside the ridged label 
textwindow = Text(frame, height=20, width=100, relief="ridge", bg='light grey', bd=4, font=("Arial", 16))
textwindow.grid(row=3, column=0, sticky='nsew')
textwindow.insert('1.0', 'first line \t\ttabbed 1\n')
textwindow.insert('2.end', 'second line \t\ttabbed text 2\n')
textwindow.insert('3.end', 'third line \t\ttabbed text 3\n')

#textwindow.replace('3.0', '3.end', 'added line after delete')

window.mainloop()
