#!/bin/python3

import os
import traceback
import time
import socket
import sys
from util import testapp 

span = 30
freq = 5900
tone_freq = 1004
pwr = 6
try:


    #build client object
    test = testapp.TestApp()

    # connect to the server
    test.connectServer()

    test.sendStartCW(tone_freq, span, pwr)
    time.sleep(3)

    resp, freq_array, power_array = test.sendGetData(freq, span)

    print("freq_array ", freq_array);
    print("power_array ", power_array);

    test.sendStopGen()

    test.disconnectServer()


except Exception as e:

    print(traceback.format_exc())
    print("**Error: " + str(e))




